services:
  model_pipeline:
    build: .
    container_name: model_pipeline_container
    volumes:
      - .:/model_pipeline  # Mount local directory into the container
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "scripts/fetch_gmail_threads.py"]
